### ISSUE TITLE
Default styling has move number tiny and illegible

### ISSUE THREAD

**Issue by amj** [Kashomon/glift#113]
here's a screenshot from stock chrome on linux at 100% zoom; the move number is basically illegible.
![screenshot from 2015-02-13 13 17 29]

(https://cloud.githubusercontent.com/assets/422841/6195449/1c904dfc-b383-11e4-8dae-d69b2ac52080.png)

**Comment by amj** [comment]
(this is a non-retina display)

**Comment by Kashomon** [comment]
Should be fixed now in 1.0.5
