### ISSUE TITLE
Board markup draw canceled by hover during navigation

### ISSUE THREAD

**Issue by yewang** [Kashomon/glift#116]
If you have the mouse hovering over the board (producing a transparent overlay of a stone) while navigating through the game using the arrow keys, the drawing of board markup seems to be canceled at that location (and some other locations). The markup remains missing even after you move the mouse, but it can be fixed by moving the mouse off of the board, then navigating away from and back to the affected board position.

**Comment by Kashomon** [comment]
Thanks for the report -- I know it's been a while, but I should have a fix now. The solution I came up with was to cancel the hover stones while using the mousewheel or the arrow-buttons.
