### ISSUE TITLE
Bounds bug with AB/AW?

### ISSUE THREAD

**Issue by marcelgruenauer** [Kashomon/glift#121]
With this data:

    (;AB[rr];W[cc])"

I get a "Cannot read property 'ALL' of undefined" in glift_1_0_4.min.js line 314.

With this it works:

    (;AB[rr];W[qq])"

That's using the default glift.enums.boardRegions.AUTO. The first case works fine with glift.enums.boardRegions.ALL.

Could this be because AB/AW determines which region to display, but then the first move is outside that region?

**Comment by Kashomon** [comment]
Ah, turns out it was an untested code path. Now, in the out-of-bounds case, it should default to showing the whole board.  Fixed in 1.0.5
