### ISSUE TITLE
rectangles don't work with AB[] and AW[]

### ISSUE THREAD

**Issue by marcelgruenauer** [Kashomon/glift#123]
WIth this file:

    (;AB[pb:sb][oc][sc][nd][oe:pe]AW[pa:qa][nb:ob][mc:me][qc:rc][re][nf][pf:pg][rg];B[rd]GB[])

the error is:

    Uncaught Unknown SGF Coord length: 5for property pb:sb
     glift.util.pointFromSgfCoord
     glift.sgf.allSgfCoordsToPoints
     a.getPlacementsAsPoints
     a.loadStonesFromMovetree
     glift.rules.goban.getFromMoveTree
     a.initialize
     a.initOptions
     glift.controllers.staticProblem
     glift.widgets.BaseWidget.draw
     (anonymous function)
     glift.widgets.WidgetManager.loadSgfString
     (anonymous function)
     glift.widgets.WidgetManager.draw
     glift.widgets.createbug.html:28 (anonymous function)

SmartGo for Mac saves files this way.

**Comment by Kashomon** [comment]
Ugh. I'll try to have a fix out tomorrow. Thanks for the bug report.

**Comment by Kashomon** [comment]
Ok, this is fixed @ head and will be out in 1.0.5.  I've used your example as a testcase, thanks.

**Comment by marcelgruenauer** [comment]
Thank you!
