### ISSUE TITLE
"YounggilLesson" Example Crashes

### ISSUE THREAD

**Issue by yewang** [Kashomon/glift#124]
The lesson example at
http://www.gliftgo.com/#YounggilLesson
crashes when switching to panels 5 or 31.

This seems to be readily reproducible in both Chrome on Windows and Firefox on Linux.

In Chrome, this error message is left in the console:
Uncaught TypeError: Cannot read property 'getChild' of null

**Comment by Kashomon** [comment]
Thanks for the feedback. I'll take a look.
