### ISSUE TITLE
SGF FF[1]-FF[3] support

### ISSUE THREAD

**Issue by yewang** [Kashomon/glift#125]
Lowercase letters should be allowed in property identifiers in order to support SGF FF[1]-FF[3].

This is related to this closed issue, where I left a comment:
https://github.com/Kashomon/glift/issues/101

For SGF files with FF[1] through FF[3], lowercase letters are allowed in the property identifier names, but are simply ignored. Hence, the property id "CoPyright" should simply be interpreted as "CP" for such files. Also, note that if an SGF file omits the FF property, FF[1] should be assumed by default.

The guide for converting older file formats discusses this issue:
http://www.red-bean.com/sgf/converting.html

**Comment by Kashomon** [comment]
Yes I agree. Thanks for the link. I agree that Glift should support FF3
