### ISSUE TITLE
Run Qunit tests in TravisCI

### ISSUE THREAD

**Issue by pconerly** [Kashomon/glift#134]
What do you think? It'd hopefully encourage more tests and it'd make it easier for you to verify PRs from all those shady developers on github, like me. :D

**Comment by Kashomon** [comment]
Been looking into this.  The easies way forward would be to split the tests into to unit tests and integration tests so I can run the former with a headless V8 (phantom). That's probably a good thing to do anyway.

**Comment by Kashomon** [comment]
Note to self: http://phantomjs.org/headless-testing.html

**Comment by Kashomon** [comment]
Also: https://github.com/Krinkle/travis-ci-node-and-browser-qunit

**Comment by Kashomon** [comment]
Done!!
