### ISSUE TITLE
Allow trailing commas in javascript

### ISSUE THREAD

**Issue by pconerly** [Kashomon/glift#137]
Is there a setting in closure to allow trailing commas?  I don't think you're trying to support IE8 anyway, and trailing commas are the bomb.   [Airbnb's style guide on trailing commas](https://github.com/airbnb/javascript#19.2).

If we're worried about compatibility, we could also think about compiling this project with [webpack](https://webpack.github.io/) instead of closure. That could be a benefit in it's own right--- having java & python as project dependencies is a little silly and webpack is great tool.

**Comment by Kashomon** [comment]
Definitely. Just have to find the right flag for the closure compiler.
