### ISSUE TITLE
Error parsing paths

### ISSUE THREAD

**Issue by placz** [Kashomon/glift#147]
Looking at http://www.gliftgo.com/#YounggilLesson, this fatal error is encountered on diagram 10:

glift.min.js:240 Uncaught Error: Was expecting number but found 1-49 for path: 1-49
 glift.rules.treepath.parseFragment @
 glift.min.js:240glift.rules.treepath.parseInitialPath @
 glift.min.js:239glift.controllers.BaseController.initialize @
 glift.min.js:253glift.controllers.BaseController.initOptions
 @ glift.min.js:253glift.controllers.gameViewer
 @ glift.min.js:266glift.widgets.BaseWidget.draw
 @ glift.min.js:312(anonymous function)
 @ glift.min.js:327glift.widgets.WidgetManager.loadSgfString
 @ glift.min.js:331(anonymous function)
 @ glift.min.js:327glift.widgets.WidgetManager.draw
 @ glift.min.js:327glift.widgets.WidgetManager.nextSgfInternal_
 @ glift.min.js:333glift.widgets.WidgetManager.nextSgf
 @ glift.min.js:333glift.api.iconActionDefaults.chevron-right.click
 @ glift.min.js:336(anonymous function) @ glift.min.js:138

**Comment by Kashomon** [comment]
Great. Thanks for the report. Should be fixed @ https://github.com/Kashomon/glift-web with https://github.com/Kashomon/glift-web/commit/48e0f5ffd7e3e2135638c5522751fb0191593eb3. I changed the path-parsing logic.
