### ISSUE TITLE
Cannot view Glift on my Firefox browser (Chrome is OK)

### ISSUE THREAD

**Issue by trantue** [Kashomon/glift#165]
I've used glift for a couple month and I like it. It's working perfectly fine in Chrome. But today I found that Glift doesn't apprear on my Firefox (and IE) Browser.

When I use Firefox to browse gogameguru.com, Glift apprear nicely. But my site is not. I don't even have an idea what's going on. Pls help :((

http://blogcovay.com/ing-cup-co-vay-han-quoc-va-park-junghwan-9p/
http://blogcovay.com/bo-co-the-song-chet-so-cap-1-50-bai/

**Comment by trantue** [comment]
My friend told me that he can see Glift on his laptop's Firefox Browser. 

Then what happen with my computer? (and maybe someone else, too)

**Comment by Kashomon** [comment]
Hm. it seems to be working fine on my version of firefox too. What's operating system (+version) and what version of firefox are you using?

**Comment by trantue** [comment]
I use Window 10 Pro 64-bit. And the latest version of Firefox (just downloaded it today). 

Maybe there's something wrong with my site or hosting. My friends have no trouble access Glift on gogameguru.com with any browser. But sometime they cannot view Glift on blogcovay.com in Firefox and sometime with Chrome, too (and also IE).

**Comment by Kashomon** [comment]
Tried debugging this, but couldn't find any problems. Let me know if you discover more problems.
