### ISSUE TITLE
Add Support For Ko

### ISSUE THREAD

**Issue by Kashomon** [Kashomon/glift#45]
There is no support currently for Ko. It would be nice to display this information.  Not a high priority currently.

**Comment by ricalamino** [comment]
Hi,
I am embeding Glift in [my pages](http://go.alamino.net/playgoto) where I teach Go, however I noticed that ko was not supported, so I did not use Glift there. It would be very nice to have this feature implemented. Congratulations about your amazing work at Glift!
 
Thank you.

**Comment by Kashomon** [comment]
Hello. I've been working to add Ko in https://github.com/Kashomon/glift/commit/c8023ca5539786bd0df7edbe7a2208119b17aa8e. I still need to add UI support.

**Comment by Kashomon** [comment]
This is more or less done and should be much easier now that the board supports the flattener.
